
name: Local CI (fast)

on:
  push:
    branches-ignore: ["main"]
  pull_request:

jobs:
  local:
    runs-on: [self-hosted, fedora]
    env:
      MPLBACKEND: Agg

    steps:
      - uses: actions/checkout@v4

      - name: Ensure ANTLR installed
        run: |
          if [ ! -f antlr-4.13.1-complete.jar ]; then
            curl -O https://www.antlr.org/download/antlr-4.13.1-complete.jar
          fi
      
      - name: Generate ANTLR parser
        run: make gen-parser

      - name: Create venv
        run: python3 -m venv .venv
      
      - name: Activate venv
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      
      - name: Install deps
        run: |
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install -e .[dev]

      - name: Run unit tests
        run: pytest -m "unit" --disable-warnings --cov=logictree --cov-report=html --cov-report=xml:coverage.xml --cov-append --cov-report=term --maxfail=9000 -o console_output_style=classic || true

      - name: Run integration tests
        run: pytest -m "integration and not requires_graphviz" --cov=logictree --cov-report=html --cov-report=xml:coverage.xml --cov-append --cov-report=term --maxfail=9000 --disable-warnings -o console_output_style=classic || true

      #- name: Run visualization tests
      #  run: pytest -m "visual" --disable-warnings --maxfail=9000 -o console_output_style=classic || true
      #- name: Generate coverage reports
      #  run: |
      #    coverage combine
      #    coverage xml -o coverage.xml
      #    coverage html
      #    coverage report
        #run: |
          #pytest -q -m "unit or props or diff" \
          #  --tb=short \
          #  --cov=logictree \
          #  --cov-fail-under=85 \
          #  --cov-report=html \
          #  --cov-report=xml:coverage.xml \
          #  --cov-report=term-missing \
          #  --maxfail=1 \
          #  --disable-warnings || true

      - name: Check coverage file
        run: ls -lh coverage.xml || (echo "Coverage file missing!" && exit 1)

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          #token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov

      - name: Coverage summary
        if: always()
        run: |
          echo "Coverage summary:"
          grep -A2 "TOTAL" coverage.xml || true


